# Generated by Django 4.0.5 on 2022-07-07 02:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='dataatualizado',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='datacriado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
