# Generated by Django 4.0.5 on 2022-07-04 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos_treinos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alunotreino',
            name='exercicios',
        ),
    ]
