# Generated by Django 4.0.5 on 2022-07-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('datacriado', models.DateTimeField(auto_now_add=True)),
                ('dataatualizado', models.DateTimeField(null=True)),
            ],
        ),
    ]
