# Generated by Django 4.0.5 on 2022-07-07 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercicios', '0001_initial'),
        ('alunos_treinos', '0003_alunotreino_ativo_alunotreino_dataatualizado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoTreinoExercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeticoes', models.IntegerField()),
                ('peso', models.IntegerField()),
                ('tipopeso', models.CharField(choices=[('UN', 'Unidade'), ('TOT', 'Total'), ('NA', 'Não se aplica')], default='NA', max_length=200)),
                ('datacriado', models.DateTimeField(auto_now_add=True)),
                ('dataatualizado', models.DateTimeField(null=True)),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercicios.exercicio')),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos_treinos.alunotreino')),
            ],
        ),
    ]
